services:
  traefik:
    image: traefik:v2.8
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"     # adjust the first number to specify the local port 
      # - "8080:8080"  # Uncomment to expose Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web
    restart: always
  
  frontend:
    image: rakurtz/shellycontrol-frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=4000"
    env_file:
      - configuration.env
    networks:
      - web
    restart: always
    
  backend:
    image: rakurtz/shellycontrol-backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=api-stripprefix"
    volumes:
      - ./my_shellies_and_lamps.yaml:/app/my_shellies_and_lamps.yaml
    env_file:
      - configuration.env
    networks:
      - web
    restart: always


networks:
  web:
    # external: true
