shellies:
- id: 1
  ip: 192.168.0.214
  device_name: loggia_wohnzimmer
- id: 0
  ip: 192.168.0.239
  device_name: weinregal
- id: 4
  ip: 192.168.0.93
  device_name: bad
- id: 2
  ip: 192.168.0.61
  device_name: küche
- id: 3
  ip: 192.168.0.38
  device_name: flur
- id: 5
  ip: 192.168.0.236
  device_name: schlafzimmer
lamps:
- id: 0
  name: Küche
  members:
  - device_id: 2
    lane: 0
- id: 1
  name: Flur
  members:
  - device_id: 3
    lane: 0
  - device_id: 3
    lane: 1
  - device_id: 4
    lane: 0
- id: 2
  name: Loggia
  members:
  - device_id: 1
    lane: 0
  - device_id: 1
    lane: 1
- id: 3
  name: Wohnzimmer
  members:
  - device_id: 1
    lane: 2
  - device_id: 1
    lane: 3
- id: 4
  name: Weinregal
  members:
  - device_id: 0
    lane: 0
  - device_id: 0
    lane: 1
- id: 5
  name: Schlafzimmer
  members:
  - device_id: 5
    lane: 0
- id: 6
  name: Bad
  members:
  - device_id: 4
    lane: 1
